{% set name = "crawlerdetect" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crawlerdetect-{{ version }}.tar.gz
  sha256: a45286c525542900013849c57b2ac59054821ff7e641e871b740b7e2f34afdf6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - crawlerdetect
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/moskrc/CrawlerDetect
  summary: CrawlerDetect is a Python class for detecting bots/crawlers/spiders via the user agent.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
