{% set name = "crawlerdetect" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crawlerdetect-{{ version }}.tar.gz
  sha256: a269289943f6b2a8f33ed5b9a09591b6dae0e45c0c19a0d9c5ef07f5c518575c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4,<4.0
    - pip
  run:
    - python >=3.4,<4.0

test:
  imports:
    - crawlerdetect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moskrc/CrawlerDetect
  summary: CrawlerDetect is a Python class for detecting bots/crawlers/spiders via the user agent.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
